language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro
  - ROS_DISTRO=indigo
notifications:
  - email: false

before_install:
  - CI_SOURCE_PATH=$(pwd)
  - REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo pip install codecov

install:
  - source <(wget -O- https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/scripts/bootstrap-ros-$ROS_DISTRO)
  - tue-get install ros-${REPOSITORY_NAME}
  - source ~/.tue/setup.bash # source all target setup files

before_script:
  - cd ${TUE_SYSTEM_DIR}/src

  # Link the repo we are testing to the new workspace
  - rm -rf $REPOSITORY_NAME
  - ln -s $CI_SOURCE_PATH .
  - ls -l
  - cd .. # go to the catkin workspace

script:
  - catkin_make -j2
  - catkin_make install   # installing the package
  - catkin_make tests     # build the tests
  - catkin_make run_tests # and run them
  - roscd robot_smach_states
  - coverage run src/robot_smach_states/util/designators/arm.py
  - coverage run --append src/robot_smach_states/util/designators/checks.py
  - coverage run --append src/robot_smach_states/util/designators/core.py
  - coverage run --append src/robot_smach_states/util/designators/decorators.py
  - coverage run --append src/robot_smach_states/util/designators/ed_designators.py
  - coverage run --append src/robot_smach_states/util/designators/tests.py
  - coverage run --append src/robot_smach_states/util/designators/utility.py
  - coverage run --append src/robot_smach_states/human_interaction/human_interaction.py
  - coverage run --append src/robot_smach_states/manipulation/manipulation.py
  - python -c "import robot_smach_states as states"

after_success:
  - codecov
