language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro
notifications:
  - email: false

before_install:
  - CI_SOURCE_PATH=$(pwd)
  - REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  
before_install:
  - pip install codecov
  
install:
  - source <(wget -O- https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/scripts/bootstrap-ros-$ROS_DISTRO)
  - tue-get install ros-${REPOSITORY_NAME}
  - source ~/.tue/setup.bash # source all target setup files

before_script:
  - cd ${TUE_SYSTEM_DIR}/src

  # Link the repo we are testing to the new workspace
  - rm -rf $REPOSITORY_NAME
  - ln -s $CI_SOURCE_PATH .
  - ls -l
  - cd .. # go to the catkin workspace

script:
  - catkin_make -j2
  - catkin_make install   # installing the package
  - catkin_make tests     # build the tests
  - catkin_make run_tests # and run them
  - rosrun robot_smach_states arm.py
  - rosrun robot_smach_states checks.py
  - rosrun robot_smach_states collection_designators.py
  - rosrun robot_smach_states core.py
  - rosrun robot_smach_states decorators.py
  - rosrun robot_smach_states ed_designators.py
  - rosrun robot_smach_states tests.py
  - rosrun robot_smach_states human_interaction.py
  - pushd .
  - roscd robot_smach_states/src/robot_smach_states/util/designators/
  - python utility.py
  - popd
  
after_success:
  - codecov
