sudo: true

language: cpp

services:
  - docker

before_install:
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/install-package.sh
  - wget https://raw.githubusercontent.com/tue-robotics/tue-env/master/ci/build-package.sh
  # Determine packages modified in this commit
  - PACKAGES=`git diff-tree --name-only $TRAVIS_COMMIT | xargs ls -dl 2>/dev/null |  grep "^d" | awk '{print $NF}' `

script: 
  - 'for PACKAGE in $PACKAGES;
     do 
     bash install-package.sh --package=$PACKAGE --branch=$TRAVIS_BRANCH --commit=$TRAVIS_COMMIT &&
     bash build-package.sh --package=$PACKAGE;
     done'
