language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro
notifications:
  email: false

before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"

install:
  - export TUE_ENV=$ROS_DISTRO
  - source <(wget -O- https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/scripts/bootstrap)
  - tue-get install ros-robot_skills
  - tue-get install ros-robot_smach_states
  - tue-get install ros-${REPOSITORY_NAME}

before_script:
  - source ~/.tue/setup.bash # source ROS
  - cd ${TUE_SYSTEM_DIR}/src

  # Link the repo we are testing to the new workspace
  - rm -rf $REPOSITORY_NAME
  - ln -s $CI_SOURCE_PATH .
  - ls -l
  - cd .. # go to the catkin workspace
  - rospack list

script:
  - catkin_make
  - catkin_make install   # installing the package
  - catkin_make tests     # build the tests
  - catkin_make run_tests # and run them
  - roscore >> /dev/null & #Obvisousle we need a roscore
  - rosrun tf_server tf_server >> /dev/null & #Robot keeps waiting for this
  - roscd tue_robocup
  - ./open_door.sh  >> /dev/null & #Make it look that the door is open so we can drive in. Its a bit hacky
  - roscd challenge_manipulation
  - rosrun challenge_manipulation manipulation.py mockbot
  - roscd challenge_navigation
  - rosrun challenge_navigation challenge_navigation.py mockbot
  - roscd challenge_person_recognition
  - rosrun challenge_person_recognition person_recognition mockbot
  - roscd challenge_rips
  - rosrun challenge_rips rips.py mockbot
  - roscd challenge_robonurse
  - rosrun challenge_robonurse challenge_robonurse.py mockbot
  - roscd challenge_speech_recognition
  - rosrun challenge_speech_recognition 1_direct_speech_recognition.py mockbot
  - roscd challenge_speech_recognition
  - rosrun challenge_speech_recognition 2_indirect_speech_recognition.py mockbot
