sudo: required
dist: trusty
language: generic
env:
  matrix:
    - USE_DEB=true  ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    #- USE_DEB=true  ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
  #- ROS_DISTRO=indigo
  #- ROS_DISTRO=jade
notifications:
  email:
    on_success: change # [always|never|change], default=change
    on_failure: change # [always|never|change], default=always

before_install:
  - CI_SOURCE_PATH=$(pwd)
  - REPOSITORY_NAME=${PWD##*/}
  - ROS_DISTRO="kinetic"
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"

install:
  - sudo apt-get install ros-indigo-ros-base  # This is necessary for tue-env
  - source <(wget -O- https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/scripts/bootstrap-ros-$ROS_DISTRO)
  - tue-get install ros-$REPOSITORY_NAME
  - source ~/.tue/setup.bash # source all target setup files

before_script:
  # remove the tue-get version of our repo with the travis one
  - cd "$TUE_ENV_DIR/repos/https_/github.com/tue-robotics"
  - mv "$REPOSITORY_NAME.git" "$REPOSITORY_NAME.old"
  - ln -s "$CI_SOURCE_PATH" "$REPOSITORY_NAME.git"

  # install travis' package dependencies
  - cd "$TUE_SYSTEM_DIR/src"
  - rm *
  - tue-get update ros-$REPOSITORY_NAME
  - ls -l

  # go to the catkin workspace
  - cd "$TUE_SYSTEM_DIR"
  - source ~/.tue/setup.bash # source once again (is this necessary?)

  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - source .ci_config/travis.sh
  # - catkin build
  #- tue-make
  #- catkin run_tests # and run them
