language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro

notifications:
  - email: false
sudo: required

before_install:
  - CI_SOURCE_PATH=$(pwd)
  - REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo pip install codecov
  
install:
  - source <(wget -O- https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/scripts/bootstrap-ros-$ROS_DISTRO)
  - tue-get install ros-${REPOSITORY_NAME}
  - source ~/.tue/setup.bash # source all target setup files
  - echo "This is an ugly hack, directly patching a file"
  - cd /opt/ros/$ROS_DISTRO/lib/python2.7/dist-packages/smach_ros
  - sudo wget https://raw.githubusercontent.com/LoyVanBeek/executive_smach/indigo-devel/smach_ros/src/smach_ros/simple_action_state.py

before_script:
  - cd ${TUE_SYSTEM_DIR}/src
  - export ROBOT_ENV=robotics_testlabs
  # Link the repo we are testing to the new workspace
  - rm -rf $REPOSITORY_NAME
  - ln -s $CI_SOURCE_PATH .
  - ls -l
  - cd .. # go to the catkin workspace

script:
  - catkin_make -j2
  - catkin_make install   # installing the package
  - catkin_make tests     # build the tests
  - roscore >> /dev/null & #Set up a roscore to run the tests with
  - catkin_make run_tests # and run them
  - roscd challenge_test/src
  - coverage run test.py mockbot
  - killall roscore #And kill the roscore afterwards
  - codecov
